### ISSUE TITLE
the last feature dimension

### ISSUE THREAD

**Issue by youmingdeng** [XinshaoAmosWang/Ranked-List-Loss-for-DML#4]
hi,  I read the paper and have a question about the feature dimension
the final dimension in the retrieval system is 512*3 = 1536dim ？？
Thanks for your reply.

**Comment by XinshaoAmosWang** [comment]
Yes, that is right. Please see our table 6 for more details. 

I am still exploring why low-level, mid-level, and high-level representations perform similarly while their concatenation performs significantly better.

**Comment by youmingdeng** [comment]
Thanks, the work is very good.
