### ISSUE TITLE
Caffe Code

### ISSUE THREAD

**Issue by say2sarwar** [XinshaoAmosWang/Ranked-List-Loss-for-DML#7]
I like your work and i want to recreate it. I need the Caffe code for academic use only. please send it to sarwar@iis.sinica.edu.tw.

The code you mention in the link; it doesn't work. I already send you an email but I think you didn't get it.

**Comment by XinshaoAmosWang** [comment]
@say2sarwar 
Many thanks for your kind interest.  I just sent you an email. Please feel free to drop me an email if you have any more questions.  Best wishes.

**Comment by say2sarwar** [comment]
Thank you so much.
